In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/processed/cleaned_us_accidents.csv'
)

In [4]:
df.head()

,ID,Severity,Start_Time,End_Time,Start_Lat,Start_Lng,Street,City,County,State,...,Year,Weekday,Is_Weekend,Temperature(C),Wind_Chill(C),Distance(km),Visibility(km),Wind_Speed(kmh),Precipitation(mm),Pressure(hPa)
0,A-75728,2,2016-11-28 16:23:04,2016-11-28 17:07:39,34.027828,-118.211700,US-101 N,Los Angeles,Los Angeles,CA,...,2016,Monday,False,16.722222,14.444444,0.016093,16.0934,8.046700,0.0,1009.982526
1,A-80191,3,2016-09-28 12:33:15,2016-09-28 13:02:57,33.937790,-117.556152,6th St,Norco,Riverside,CA,...,2016,Wednesday,False,33.277778,23.333333,0.000000,16.0934,5.632690,0.0,1013.030763
2,A-19865,3,2016-09-13 20:16:23,2016-09-13 20:46:23,38.553600,-121.690643,I-80 E,Davis,Yolo,CA,...,2016,Tuesday,False,19.000000,23.333333,0.000000,16.0934,9.334172,0.0,1014.046842
3,A-76706,3,2016-09-13 10:07:38,2016-09-13 10:37:38,33.965294,-117.326668,I-215 S,Riverside,Riverside,CA,...,2016,Tuesday,False,18.277778,23.333333,0.000000,16.0934,9.656040,0.0,1014.385535
4,A-92998,3,2016-08-27 17:56:49,2016-08-27 18:26:49,33.872711,-118.284805,Artesia Fwy E,Gardena,Los Angeles,CA,...,2016,Saturday,True,22.222222,23.888889,0.000000,16.0934,14.805928,0.0,1013.708149

In [5]:
df.columns

Index(['ID', 'Severity', 'Start_Time', 'End_Time', 'Start_Lat', 'Start_Lng',
       'Street', 'City', 'County', 'State', 'Timezone', 'Humidity(%)',
       'Wind_Direction', 'Weather_Condition', 'Amenity', 'Bump', 'Crossing',
       'Give_Way', 'Junction', 'No_Exit', 'Railway', 'Roundabout', 'Station',
       'Stop', 'Traffic_Calming', 'Traffic_Signal', 'Sunrise_Sunset', 'Hour',
       'Day', 'Month', 'Year', 'Weekday', 'Is_Weekend', 'Temperature(C)',
       'Wind_Chill(C)', 'Distance(km)', 'Visibility(km)', 'Wind_Speed(kmh)',
       'Precipitation(mm)', 'Pressure(hPa)'],
      dtype='object')

In [6]:
df.shape

(386179, 40)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386179 entries, 0 to 386178
Data columns (total 40 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   ID                 386179 non-null  object
 1   Severity           386179 non-null  int64
 2   Start_Time         386179 non-null  object
 3   End_Time           386179 non-null  object
 4   Start_Lat          386179 non-null  float64
 5   Start_Lng          386179 non-null  float64
 6   Street             386179 non-null  object
 7   City               386179 non-null  object
 8   County             386179 non-null  object
 9   State              386179 non-null  object
 10  Timezone           386179 non-null  object
 11  Humidity(%)        386179 non-null  float64
 12  Wind_Direction     386179 non-null  object
 13  Weather_Condition  386179 non-null  object
 14  Amenity            386179 non-null  bool
 15  Bump               386179 non-null  bool
 16  Crossing           386179 non-null  bool
 17  Give_Way           386179 non-null  bool
 18  Junction           386179 non-null  bool
 19  No_Exit            386179 non-null  bool
 20  Railway            386179 non-null  bool
 21  Roundabout         386179 non-null  bool
 22  Station            386179 non-null  bool
 23  Stop               386179 non-null  bool
 24  Traffic_Calming    386179 non-null  bool
 25  Traffic_Signal     386179 non-null  bool
 26  Sunrise_Sunset     386179 non-null  object
 27  Hour               386179 non-null  int64
 28  Day                386179 non-null  int64
 29  Month              386179 non-null  int64
 30  Year               386179 non-null  int64
 31  Weekday            386179 non-null  object
 32  Is_Weekend         386179 non-null  bool
 33  Temperature(C)     386179 non-null  float64
 34  Wind_Chill(C)      386179 non-null  float64
 35  Distance(km)       386179 non-null  float64
 36  Visibility(km)     386179 non-null  float64
 37  Wind_Speed(kmh)    386179 non-null  float64
 38  Precipitation(mm)  386179 non-null  float64
 39  Pressure(hPa)      386179 non-null  float64
dtypes: bool(13), float64(10), int64(5), object(12)
memory usage: 84.3+ MB

In [9]:
# нормалізація назв колонок
df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_")
)

In [11]:
df = df.rename(columns={
    'humidity(%)': 'humidity_pct',
    'temperature(c)': 'temperature_c',
    'wind_chill(c)': 'wind_chill_c',
    'distance(km)': 'distance_km',
    'visibility(km)': 'visibility_km',
    'wind_speed(kmh)': 'wind_speed_kmh',
    'precipitation(mm)': 'precipitation_mm',
    'pressure(hpa)': 'pressure_hpa'
})

In [12]:
df.columns

Index(['id', 'severity', 'start_time', 'end_time', 'start_lat', 'start_lng',
       'street', 'city', 'county', 'state', 'timezone', 'humidity_pct',
       'wind_direction', 'weather_condition', 'amenity', 'bump', 'crossing',
       'give_way', 'junction', 'no_exit', 'railway', 'roundabout', 'station',
       'stop', 'traffic_calming', 'traffic_signal', 'sunrise_sunset', 'hour',
       'day', 'month', 'year', 'weekday', 'is_weekend', 'temperature_c',
       'wind_chill_c', 'distance_km', 'visibility_km', 'wind_speed_kmh',
       'precipitation_mm', 'pressure_hpa'],
      dtype='object')

In [14]:
# cтворення основної таблиці accidents_main
accidents_main = df[[
    'id',
    'severity',
    'start_time',
    'end_time',
    'distance_km'
]]

In [15]:
accidents_main.head()

        id  severity           start_time             end_time  distance_km
0  A-75728         2  2016-11-28 16:23:04  2016-11-28 17:07:39     0.016093
1  A-80191         3  2016-09-28 12:33:15  2016-09-28 13:02:57     0.000000
2  A-19865         3  2016-09-13 20:16:23  2016-09-13 20:46:23     0.000000
3  A-76706         3  2016-09-13 10:07:38  2016-09-13 10:37:38     0.000000
4  A-92998         3  2016-08-27 17:56:49  2016-08-27 18:26:49     0.000000

In [16]:
accidents_main.shape

(386179, 5)

In [17]:
accidents_main.isna().sum()

id             0
severity       0
start_time     0
end_time       0
distance_km    0
dtype: int64

In [18]:
# cтворення таблиці location_data
location_data = df[[
    'id',
    'start_lat',
    'start_lng',
    'street',
    'city',
    'county',
    'state',
    'timezone'
]]

In [19]:
location_data.head()

,id,start_lat,start_lng,street,city,county,state,timezone
0,A-75728,34.027828,-118.211700,US-101 N,Los Angeles,Los Angeles,CA,US/Pacific
1,A-80191,33.937790,-117.556152,6th St,Norco,Riverside,CA,US/Pacific
2,A-19865,38.553600,-121.690643,I-80 E,Davis,Yolo,CA,US/Pacific
3,A-76706,33.965294,-117.326668,I-215 S,Riverside,Riverside,CA,US/Pacific
4,A-92998,33.872711,-118.284805,Artesia Fwy E,Gardena,Los Angeles,CA,US/Pacific

In [20]:
location_data.shape

(386179, 8)

In [22]:
# cтворення таблиці weather_data
weather_data = df[[
    'id',
    'weather_condition',
    'temperature_c',
    'wind_chill_c',
    'wind_direction',
    'wind_speed_kmh',
    'visibility_km',
    'precipitation_mm',
    'pressure_hpa',
    'humidity_pct'
]]

In [23]:
weather_data.head()

,id,weather_condition,temperature_c,wind_chill_c,wind_direction,wind_speed_kmh,visibility_km,precipitation_mm,pressure_hpa,humidity_pct
0,A-75728,Clear,16.722222,14.444444,Calm,8.046700,16.0934,0.0,1009.982526,53.0
1,A-80191,Clear,33.277778,23.333333,Variable,5.632690,16.0934,0.0,1013.030763,26.0
2,A-19865,Clear,19.000000,23.333333,SSW,9.334172,16.0934,0.0,1014.046842,52.0
3,A-76706,Overcast,18.277778,23.333333,Calm,9.656040,16.0934,0.0,1014.385535,61.0
4,A-92998,Clear,22.222222,23.888889,West,14.805928,16.0934,0.0,1013.708149,68.0

In [24]:
weather_data.shape

(386179, 10)

In [26]:
# cтворення таблиці road_conditions
road_conditions = df[[
    'id',
    'amenity',
    'bump',
    'crossing',
    'give_way',
    'junction',
    'no_exit',
    'railway',
    'roundabout',
    'station',
    'stop',
    'traffic_calming',
    'traffic_signal'
]]

In [27]:
road_conditions.head()

,id,amenity,bump,crossing,give_way,junction,no_exit,railway,roundabout,station,stop,traffic_calming,traffic_signal
0,A-75728,False,False,False,False,False,False,False,False,False,False,False,False
1,A-80191,False,False,False,False,False,False,False,False,False,False,False,False
2,A-19865,False,False,False,False,False,False,False,False,False,False,False,False
3,A-76706,False,False,False,False,False,False,False,False,False,False,False,False
4,A-92998,False,False,False,False,False,False,False,False,False,False,False,False

In [28]:
road_conditions.shape

(386179, 13)

In [29]:
df.columns

Index(['id', 'severity', 'start_time', 'end_time', 'start_lat', 'start_lng',
       'street', 'city', 'county', 'state', 'timezone', 'humidity_pct',
       'wind_direction', 'weather_condition', 'amenity', 'bump', 'crossing',
       'give_way', 'junction', 'no_exit', 'railway', 'roundabout', 'station',
       'stop', 'traffic_calming', 'traffic_signal', 'sunrise_sunset', 'hour',
       'day', 'month', 'year', 'weekday', 'is_weekend', 'temperature_c',
       'wind_chill_c', 'distance_km', 'visibility_km', 'wind_speed_kmh',
       'precipitation_mm', 'pressure_hpa'],
      dtype='object')

In [30]:
# cтворення таблиці time_features
time_features = df[[
    'id',
    'sunrise_sunset',
    'hour',
    'day',
    'month',
    'year',
    'weekday',
    'is_weekend'
]]

In [31]:
time_features.head()

        id sunrise_sunset  hour  day  month  year    weekday  is_weekend
0  A-75728            Day    16   28     11  2016     Monday       False
1  A-80191            Day    12   28      9  2016  Wednesday       False
2  A-19865          Night    20   13      9  2016    Tuesday       False
3  A-76706            Day    10   13      9  2016    Tuesday       False
4  A-92998            Day    17   27      8  2016   Saturday        True

In [32]:
time_features.shape

(386179, 8)

In [33]:
# експорт таблиць у CSV для подальшої роботи

accidents_main.to_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/sql_tables/accidents_main.csv',
    index=False
)

location_data.to_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/sql_tables/location_data.csv',
    index=False
)

weather_data.to_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/sql_tables/weather_data.csv',
    index=False
)

road_conditions.to_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/sql_tables/road_conditions.csv',
    index=False
)

time_features.to_csv(
    '/Users/veronika/Documents/US_Accidents_Project/data/sql_tables/time_features.csv',
    index=False
)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 386179 entries, 0 to 386178
Data columns (total 40 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   id                 386179 non-null  object
 1   severity           386179 non-null  int64
 2   start_time         386179 non-null  object
 3   end_time           386179 non-null  object
 4   start_lat          386179 non-null  float64
 5   start_lng          386179 non-null  float64
 6   street             386179 non-null  object
 7   city               386179 non-null  object
 8   county             386179 non-null  object
 9   state              386179 non-null  object
 10  timezone           386179 non-null  object
 11  humidity_pct       386179 non-null  float64
 12  wind_direction     386179 non-null  object
 13  weather_condition  386179 non-null  object
 14  amenity            386179 non-null  bool
 15  bump               386179 non-null  bool
 16  crossing           386179 non-null  bool
 17  give_way           386179 non-null  bool
 18  junction           386179 non-null  bool
 19  no_exit            386179 non-null  bool
 20  railway            386179 non-null  bool
 21  roundabout         386179 non-null  bool
 22  station            386179 non-null  bool
 23  stop               386179 non-null  bool
 24  traffic_calming    386179 non-null  bool
 25  traffic_signal     386179 non-null  bool
 26  sunrise_sunset     386179 non-null  object
 27  hour               386179 non-null  int64
 28  day                386179 non-null  int64
 29  month              386179 non-null  int64
 30  year               386179 non-null  int64
 31  weekday            386179 non-null  object
 32  is_weekend         386179 non-null  bool
 33  temperature_c      386179 non-null  float64
 34  wind_chill_c       386179 non-null  float64
 35  distance_km        386179 non-null  float64
 36  visibility_km      386179 non-null  float64
 37  wind_speed_kmh     386179 non-null  float64
 38  precipitation_mm   386179 non-null  float64
 39  pressure_hpa       386179 non-null  float64
dtypes: bool(13), float64(10), int64(5), object(12)
memory usage: 84.3+ MB

In [35]:
df['weather_condition'].unique()

array(['Clear', 'Overcast', 'Mostly Cloudy', 'Partly Cloudy', 'Haze',
       'Light Freezing Drizzle', 'Light Rain', 'Scattered Clouds', 'Fair',
       'Heavy Rain', 'Smoke', 'Widespread Dust', 'Rain', 'Light Snow',
       'Light Thunderstorms and Rain', 'Drizzle', 'Mist', 'Cloudy',
       'Snow', 'Fog', 'Fair / Windy', 'Rain Showers', 'Thunderstorm',
       'Heavy Thunderstorms and Rain', 'Light Drizzle', 'T-Storm',
       'Light Freezing Rain', 'Thunder', 'Patches of Fog',
       'Thunderstorms and Rain', 'Light Rain Showers', 'Shallow Fog',
       'Sand', 'Light Ice Pellets', 'Squalls', 'Heavy Drizzle',
       'Heavy Snow', 'Light Freezing Fog', 'Rain / Windy',
       'Partly Cloudy / Windy', 'Heavy T-Storm',
       'Thunder in the Vicinity', 'Light Rain with Thunder',
       'Cloudy / Windy', 'Mostly Cloudy / Windy',
       'Showers in the Vicinity', 'Haze / Windy', 'N/A Precipitation',
       'Light Rain / Windy', 'Heavy Rain / Windy', 'Light Snow / Windy',
       'Wintry Mix', 'Snow and Sleet', 'T-Storm / Windy',
       'Heavy T-Storm / Windy', 'Blowing Dust / Windy', 'Sleet',
       'Snow / Windy', 'Freezing Rain', 'Fog / Windy',
       'Light Snow and Sleet', 'Drizzle and Fog',
       'Sand / Dust Whirlwinds', 'Drizzle / Windy', 'Thunder / Windy',
       'Light Drizzle / Windy', 'Squalls / Windy', 'Light Sleet',
       'Heavy Snow / Windy', 'Wintry Mix / Windy', 'Smoke / Windy',
       'Heavy Freezing Rain', 'Blowing Snow', 'Light Rain Shower',
       'Rain Shower', 'Partial Fog', 'Sand / Dust Whirlwinds / Windy',
       'Blowing Snow / Windy', 'Blowing Dust', 'Ice Pellets',
       'Small Hail', 'Heavy Smoke', 'Heavy Thunderstorms with Small Hail',
       'Volcanic Ash', 'Heavy Freezing Drizzle', 'Light Snow Showers',
       'Light Haze', 'Funnel Cloud', 'Snow Grains',
       'Freezing Rain / Windy', 'Thunder / Wintry Mix / Windy',
       'Thunder / Wintry Mix', 'Freezing Drizzle',
       'Snow and Sleet / Windy', 'Light Rain Shower / Windy',
       'Shallow Fog / Windy', 'Snow and Thunder', 'Drifting Snow / Windy',
       'Widespread Dust / Windy', 'Light Snow and Sleet / Windy', 'Hail',
       'Sleet / Windy', 'Thunder and Hail', 'Heavy Sleet', 'Mist / Windy',
       'Sand / Windy', 'Light Snow with Thunder',
       'Light Freezing Rain / Windy', 'Patches of Fog / Windy',
       'Low Drifting Snow'], dtype=object)

У межах даного етапу було виконано підготовку структури даних для SQL-аналізу. Очищений sample датасету був розділений на окремі тематичні таблиці: accidents_main, location_data, road_conditions, time_features та weather_data. Це дозволило зробити дані більш структурованими та зручними для подальшого аналітичного дослідження.